// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC2yATxhUFYYY1L7sYWDH1vbT5Ws5Y-XQ',
    appId: '1:881562033772:web:14142f1c041a826d7a0249',
    messagingSenderId: '881562033772',
    projectId: 'flutter-app-cefe7',
    authDomain: 'flutter-app-cefe7.firebaseapp.com',
    storageBucket: 'flutter-app-cefe7.appspot.com',
    measurementId: 'G-14JL2LPK3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FSjbxGA8BdUKvYH3sWWJBqAYppfBEp4',
    appId: '1:881562033772:android:c55fd54c530caccd7a0249',
    messagingSenderId: '881562033772',
    projectId: 'flutter-app-cefe7',
    storageBucket: 'flutter-app-cefe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAetBZtZd4rBg_UZsD9RO6gpOMb7AnQSLY',
    appId: '1:881562033772:ios:9c20646a67d2ed1d7a0249',
    messagingSenderId: '881562033772',
    projectId: 'flutter-app-cefe7',
    storageBucket: 'flutter-app-cefe7.appspot.com',
    iosClientId:
        '881562033772-ek4gc81dfs26a5elnsvrmkjdcgssjd5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotMarketByFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAetBZtZd4rBg_UZsD9RO6gpOMb7AnQSLY',
    appId: '1:881562033772:ios:9c20646a67d2ed1d7a0249',
    messagingSenderId: '881562033772',
    projectId: 'flutter-app-cefe7',
    storageBucket: 'flutter-app-cefe7.appspot.com',
    iosClientId:
        '881562033772-ek4gc81dfs26a5elnsvrmkjdcgssjd5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotMarketByFlutter',
  );
}
